image: node:16.5.0
pages:
  stage: deploy
  cache:
    key:
      files:
        - package.json
        # - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - cp -a public/. dists/
    # - npm run dev
  artifacts:
    paths:
      - dists
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
